
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _global_type_t_H
#define _global_type_t_H
#ifdef __cplusplus
extern "C" {
#endif
#include "./global_type_t_tablegen.h"

#include "../wasm.h"

static global_type_t* convert_global_type_t (lua_State* __ls, int index) {
	global_type_t* dummy = (global_type_t*)lua_touserdata(__ls, index);
	if (dummy == NULL) printf("global_type_t:bad user data type.\n");
	return dummy;
}

static global_type_t* check_global_type_t(lua_State* __ls, int index) {
	global_type_t* dummy;
	luaL_checktype(__ls, index, LUA_TUSERDATA);
	dummy = (global_type_t*)luaL_checkudata(__ls, index, "global_type_t");
	if (dummy == NULL) printf("global_type_t:bad user data type.\n");
	return dummy;
}

global_type_t* push_global_type_t(lua_State* __ls) {
	lua_checkstack(__ls, 1);
	global_type_t* dummy = lua_newuserdata(__ls, sizeof(global_type_t));
	luaL_getmetatable(__ls, "global_type_t");
	lua_setmetatable(__ls, -2);
	return dummy;
}

int global_type_t_push_args(lua_State* __ls, global_type_t* _st) {
	lua_checkstack(__ls, 2);
	lua_pushinteger(__ls, _st->value_type);
	lua_pushinteger(__ls, _st->mutability);
	return 0;
}

int new_global_type_t(lua_State* __ls) {
	lua_checkstack(__ls, 2);
	enum value_type_t value_type = luaL_optinteger(__ls,-2,0);
	varuint1 mutability = luaL_optinteger(__ls,-1,0);
	global_type_t* dummy = push_global_type_t(__ls);
	dummy->value_type = value_type;
	dummy->mutability = mutability;
	return 1;
}

static int getter_global_type_t_value_type(lua_State* __ls) {
	global_type_t* dummy = check_global_type_t(__ls, 1);
	lua_pop(__ls, -1);
	lua_pushinteger(__ls, dummy->value_type);
	return 1;
}
static int getter_global_type_t_mutability(lua_State* __ls) {
	global_type_t* dummy = check_global_type_t(__ls, 1);
	lua_pop(__ls, -1);
	lua_pushinteger(__ls, dummy->mutability);
	return 1;
}

static int setter_global_type_t_value_type(lua_State* __ls) {
	global_type_t* dummy = check_global_type_t(__ls, 1);
	dummy->value_type = luaL_checkinteger(__ls, 2);
	lua_settop(__ls, 1);
	return 1;
}
static int setter_global_type_t_mutability(lua_State* __ls) {
	global_type_t* dummy = check_global_type_t(__ls, 1);
	dummy->mutability = luaL_checkinteger(__ls, 2);
	lua_settop(__ls, 1);
	return 1;
}

static const luaL_Reg global_type_t_methods[] = {
	{"new", new_global_type_t},
	{"set_value_type", setter_global_type_t_value_type},
	{"set_mutability", setter_global_type_t_mutability},
	{"value_type", getter_global_type_t_value_type},
	{"mutability", getter_global_type_t_mutability},
	{0,0}
};

static const luaL_Reg global_type_t_meta[] = {
	{0, 0}
};

int global_type_t_register(lua_State* __ls) {
	luaL_openlib(__ls, "global_type_t", global_type_t_methods, 0);
	luaL_newmetatable(__ls, "global_type_t");
	luaL_openlib(__ls, 0, global_type_t_meta, 0);
	lua_pushliteral(__ls, "__index");
	lua_pushvalue(__ls, -3);
	lua_rawset(__ls, -3);
	lua_pushliteral(__ls, "__metatable");
	lua_pushvalue(__ls, -3);
	lua_rawset(__ls, -3);
	lua_pop(__ls, 1);
return 1;
}

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


