
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _global_type_t_H
#define _global_type_t_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static global_type_t* convert_global_type_t (lua_State* __ls, int index);
static global_type_t* check_global_type_t(lua_State* __ls, int index);
global_type_t* push_global_type_t(lua_State* __ls);
int global_type_t_push_args(lua_State* __ls, global_type_t* _st);
int new_global_type_t(lua_State* __ls);
static int getter_global_type_t_value_type(lua_State* __ls);
static int getter_global_type_t_mutability(lua_State* __ls);
static int setter_global_type_t_value_type(lua_State* __ls);
static int setter_global_type_t_mutability(lua_State* __ls);
int global_type_t_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


