
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>

#ifndef _init_expr_t_H
#define _init_expr_t_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static init_expr_t* convert_init_expr_t (lua_State* __ls, int index);
static init_expr_t* check_init_expr_t(lua_State* __ls, int index);
init_expr_t* push_init_expr_t(lua_State* __ls);
int init_expr_t_push_args(lua_State* __ls, init_expr_t* _st);
int new_init_expr_t(lua_State* __ls);
static int getter_init_expr_t_size(lua_State* __ls);
static int getter_init_expr_t_code(lua_State* __ls);
static int setter_init_expr_t_size(lua_State* __ls);
static int setter_init_expr_t_code(lua_State* __ls);
int init_expr_t_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


