
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _memory_type_t_H
#define _memory_type_t_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static memory_type_t* convert_memory_type_t (lua_State* __ls, int index);
static memory_type_t* check_memory_type_t(lua_State* __ls, int index);
memory_type_t* push_memory_type_t(lua_State* __ls);
int memory_type_t_push_args(lua_State* __ls, memory_type_t* _st);
int new_memory_type_t(lua_State* __ls);
static int getter_memory_type_t_resizable_limit(lua_State* __ls);
static int setter_memory_type_t_resizable_limit(lua_State* __ls);
int memory_type_t_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


