
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _resizable_limit_t_H
#define _resizable_limit_t_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static resizable_limit_t* convert_resizable_limit_t (lua_State* __ls, int index);
static resizable_limit_t* check_resizable_limit_t(lua_State* __ls, int index);
resizable_limit_t* push_resizable_limit_t(lua_State* __ls);
int resizable_limit_t_push_args(lua_State* __ls, resizable_limit_t* _st);
int new_resizable_limit_t(lua_State* __ls);
static int getter_resizable_limit_t_flags(lua_State* __ls);
static int getter_resizable_limit_t_initial(lua_State* __ls);
static int getter_resizable_limit_t_maximum(lua_State* __ls);
static int setter_resizable_limit_t_flags(lua_State* __ls);
static int setter_resizable_limit_t_initial(lua_State* __ls);
static int setter_resizable_limit_t_maximum(lua_State* __ls);
int resizable_limit_t_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


