
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _table_type_t_H
#define _table_type_t_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static table_type_t* convert_table_type_t (lua_State* __ls, int index);
static table_type_t* check_table_type_t(lua_State* __ls, int index);
table_type_t* push_table_type_t(lua_State* __ls);
int table_type_t_push_args(lua_State* __ls, table_type_t* _st);
int new_table_type_t(lua_State* __ls);
static int getter_table_type_t_element_type(lua_State* __ls);
static int getter_table_type_t_resizable_limit(lua_State* __ls);
static int setter_table_type_t_element_type(lua_State* __ls);
static int setter_table_type_t_resizable_limit(lua_State* __ls);
int table_type_t_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


