
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>

#ifndef _W_Data_Segment_H
#define _W_Data_Segment_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static W_Data_Segment* convert_W_Data_Segment (lua_State* __ls, int index);
static W_Data_Segment* check_W_Data_Segment(lua_State* __ls, int index);
W_Data_Segment* push_W_Data_Segment(lua_State* __ls);
int W_Data_Segment_push_args(lua_State* __ls, W_Data_Segment* _st);
int new_W_Data_Segment(lua_State* __ls);
static int getter_W_Data_Segment_index(lua_State* __ls);
static int getter_W_Data_Segment_offset(lua_State* __ls);
static int getter_W_Data_Segment_size(lua_State* __ls);
static int getter_W_Data_Segment_data(lua_State* __ls);
static int setter_W_Data_Segment_index(lua_State* __ls);
static int setter_W_Data_Segment_offset(lua_State* __ls);
static int setter_W_Data_Segment_size(lua_State* __ls);
static int setter_W_Data_Segment_data(lua_State* __ls);
int W_Data_Segment_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


