
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _W_Elem_Segment_H
#define _W_Elem_Segment_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static W_Elem_Segment* convert_W_Elem_Segment (lua_State* __ls, int index);
static W_Elem_Segment* check_W_Elem_Segment(lua_State* __ls, int index);
W_Elem_Segment* push_W_Elem_Segment(lua_State* __ls);
int W_Elem_Segment_push_args(lua_State* __ls, W_Elem_Segment* _st);
int new_W_Elem_Segment(lua_State* __ls);
static int getter_W_Elem_Segment_index(lua_State* __ls);
static int getter_W_Elem_Segment_offset(lua_State* __ls);
static int getter_W_Elem_Segment_num_length(lua_State* __ls);
static int getter_W_Elem_Segment_elems(lua_State* __ls);
static int setter_W_Elem_Segment_index(lua_State* __ls);
static int setter_W_Elem_Segment_offset(lua_State* __ls);
static int setter_W_Elem_Segment_num_length(lua_State* __ls);
static int setter_W_Elem_Segment_elems(lua_State* __ls);
int W_Elem_Segment_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


