
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _W_Function_Body_H
#define _W_Function_Body_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static W_Function_Body* convert_W_Function_Body (lua_State* __ls, int index);
static W_Function_Body* check_W_Function_Body(lua_State* __ls, int index);
W_Function_Body* push_W_Function_Body(lua_State* __ls);
int W_Function_Body_push_args(lua_State* __ls, W_Function_Body* _st);
int new_W_Function_Body(lua_State* __ls);
static int getter_W_Function_Body_body_size(lua_State* __ls);
static int getter_W_Function_Body_local_count(lua_State* __ls);
static int getter_W_Function_Body_locals(lua_State* __ls);
static int getter_W_Function_Body_code(lua_State* __ls);
static int setter_W_Function_Body_body_size(lua_State* __ls);
static int setter_W_Function_Body_local_count(lua_State* __ls);
static int setter_W_Function_Body_locals(lua_State* __ls);
static int setter_W_Function_Body_code(lua_State* __ls);
int W_Function_Body_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


