
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>

#ifndef _W_Global_Entry_H
#define _W_Global_Entry_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static W_Global_Entry* convert_W_Global_Entry (lua_State* __ls, int index);
static W_Global_Entry* check_W_Global_Entry(lua_State* __ls, int index);
W_Global_Entry* push_W_Global_Entry(lua_State* __ls);
int W_Global_Entry_push_args(lua_State* __ls, W_Global_Entry* _st);
int new_W_Global_Entry(lua_State* __ls);
static int getter_W_Global_Entry_type(lua_State* __ls);
static int getter_W_Global_Entry_init(lua_State* __ls);
static int setter_W_Global_Entry_type(lua_State* __ls);
static int setter_W_Global_Entry_init(lua_State* __ls);
int W_Global_Entry_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


