
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#include "./W_Local_Entry_tablegen.h"

#include "../wasm.h"

static W_Local_Entry* convert_W_Local_Entry (lua_State* __ls, int index) {
	W_Local_Entry* dummy = (W_Local_Entry*)lua_touserdata(__ls, index);
	if (dummy == NULL) printf("W_Local_Entry:bad user data type.\n");
	return dummy;
}

static W_Local_Entry* check_W_Local_Entry(lua_State* __ls, int index) {
	W_Local_Entry* dummy;
	luaL_checktype(__ls, index, LUA_TUSERDATA);
	dummy = (W_Local_Entry*)luaL_checkudata(__ls, index, "W_Local_Entry");
	if (dummy == NULL) printf("W_Local_Entry:bad user data type.\n");
	return dummy;
}

W_Local_Entry* push_W_Local_Entry(lua_State* __ls) {
	lua_checkstack(__ls, 1);
	W_Local_Entry* dummy = lua_newuserdata(__ls, sizeof(W_Local_Entry));
	luaL_getmetatable(__ls, "W_Local_Entry");
	lua_setmetatable(__ls, -2);
	return dummy;
}

int W_Local_Entry_push_args(lua_State* __ls, W_Local_Entry* _st) {
	lua_checkstack(__ls, 2);
	lua_pushinteger(__ls, _st->count);
	lua_pushinteger(__ls, _st->type);
	return 0;
}

int new_W_Local_Entry(lua_State* __ls) {
	lua_checkstack(__ls, 2);
	varuint32 count = luaL_optinteger(__ls,-2,0);
	enum value_type_t type = luaL_optinteger(__ls,-1,0);
	W_Local_Entry* dummy = push_W_Local_Entry(__ls);
	dummy->count = count;
	dummy->type = type;
	return 1;
}

static int getter_W_Local_Entry_count(lua_State* __ls) {
	W_Local_Entry* dummy = check_W_Local_Entry(__ls, 1);
	lua_pop(__ls, -1);
	lua_pushinteger(__ls, dummy->count);
	return 1;
}
static int getter_W_Local_Entry_type(lua_State* __ls) {
	W_Local_Entry* dummy = check_W_Local_Entry(__ls, 1);
	lua_pop(__ls, -1);
	lua_pushinteger(__ls, dummy->type);
	return 1;
}

static int setter_W_Local_Entry_count(lua_State* __ls) {
	W_Local_Entry* dummy = check_W_Local_Entry(__ls, 1);
	dummy->count = luaL_checkinteger(__ls, 2);
	lua_settop(__ls, 1);
	return 1;
}
static int setter_W_Local_Entry_type(lua_State* __ls) {
	W_Local_Entry* dummy = check_W_Local_Entry(__ls, 1);
	dummy->type = luaL_checkinteger(__ls, 2);
	lua_settop(__ls, 1);
	return 1;
}

static const luaL_Reg W_Local_Entry_methods[] = {
	{"new", new_W_Local_Entry},
	{"set_count", setter_W_Local_Entry_count},
	{"set_type", setter_W_Local_Entry_type},
	{"count", getter_W_Local_Entry_count},
	{"type", getter_W_Local_Entry_type},
	{0,0}
};

static const luaL_Reg W_Local_Entry_meta[] = {
	{0, 0}
};

int W_Local_Entry_register(lua_State* __ls) {
	luaL_openlib(__ls, "W_Local_Entry", W_Local_Entry_methods, 0);
	luaL_newmetatable(__ls, "W_Local_Entry");
	luaL_openlib(__ls, 0, W_Local_Entry_meta, 0);
	lua_pushliteral(__ls, "__index");
	lua_pushvalue(__ls, -3);
	lua_rawset(__ls, -3);
	lua_pushliteral(__ls, "__metatable");
	lua_pushvalue(__ls, -3);
	lua_rawset(__ls, -3);
	lua_pop(__ls, 1);
return 1;
}


