
// automatically generated by luatablegen
#include "../lua-5.3.4/src/lua.h"
#include "../lua-5.3.4/src/lauxlib.h"
#include "../lua-5.3.4/src/lualib.h"
#include <inttypes.h>
#include <stdbool.h>
#ifndef _W_Type_Section_Entry_H
#define _W_Type_Section_Entry_H
#ifdef __cplusplus
extern "C" {
#endif

#include "../wasm.h"

static W_Type_Section_Entry* convert_W_Type_Section_Entry (lua_State* __ls, int index);
static W_Type_Section_Entry* check_W_Type_Section_Entry(lua_State* __ls, int index);
W_Type_Section_Entry* push_W_Type_Section_Entry(lua_State* __ls);
int W_Type_Section_Entry_push_args(lua_State* __ls, W_Type_Section_Entry* _st);
int new_W_Type_Section_Entry(lua_State* __ls);
static int getter_W_Type_Section_Entry_form(lua_State* __ls);
static int getter_W_Type_Section_Entry_param_count(lua_State* __ls);
static int getter_W_Type_Section_Entry_param_types(lua_State* __ls);
static int getter_W_Type_Section_Entry_return_count(lua_State* __ls);
static int getter_W_Type_Section_Entry_return_types(lua_State* __ls);
static int setter_W_Type_Section_Entry_form(lua_State* __ls);
static int setter_W_Type_Section_Entry_param_count(lua_State* __ls);
static int setter_W_Type_Section_Entry_param_types(lua_State* __ls);
static int setter_W_Type_Section_Entry_return_count(lua_State* __ls);
static int setter_W_Type_Section_Entry_return_types(lua_State* __ls);
int W_Type_Section_Entry_register(lua_State* __ls);

#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard


