// automatically generated by luatablegen

#ifndef _WASM_TABLES_AGGR_H
#define _WASM_TABLES_AGGR_H
#ifdef __cplusplus
extern "C" {
#endif
#include "./init_expr_t_tablegen.h"
#include "./resizable_limit_t_tablegen.h"
#include "./global_type_t_tablegen.h"
#include "./table_type_t_tablegen.h"
#include "./memory_type_t_tablegen.h"
#include "./W_Type_Section_Entry_tablegen.h"
#include "./W_Type_Section_tablegen.h"
#include "./W_Import_Section_Entry_tablegen.h"
#include "./W_Import_Section_tablegen.h"
#include "./W_Function_Section_tablegen.h"
#include "./W_Table_Section_tablegen.h"
#include "./W_Memory_Section_tablegen.h"
#include "./W_Global_Entry_tablegen.h"
#include "./W_Global_Section_tablegen.h"
#include "./W_Export_Entry_tablegen.h"
#include "./W_Export_Section_tablegen.h"
#include "./W_Start_Section_tablegen.h"
#include "./W_Elem_Segment_tablegen.h"
#include "./W_Element_Section_tablegen.h"
#include "./W_Local_Entry_tablegen.h"
#include "./W_Function_Body_tablegen.h"
#include "./W_Code_Section_tablegen.h"
#include "./W_Data_Segment_tablegen.h"
#include "./W_Data_Section_tablegen.h"
#include "./Wasm_Module_tablegen.h"
void reg_tablegen_tables(lua_State* __ls);
#ifdef __cplusplus
}
#endif //end of extern c
#endif //end of inclusion guard

