// automatically generated by luatablegen

#include "./init_expr_t_tablegen.h"
#include "./resizable_limit_t_tablegen.h"
#include "./global_type_t_tablegen.h"
#include "./table_type_t_tablegen.h"
#include "./memory_type_t_tablegen.h"
#include "./W_Type_Section_Entry_tablegen.h"
#include "./W_Type_Section_tablegen.h"
#include "./W_Import_Section_Entry_tablegen.h"
#include "./W_Import_Section_tablegen.h"
#include "./W_Function_Section_tablegen.h"
#include "./W_Table_Section_tablegen.h"
#include "./W_Memory_Section_tablegen.h"
#include "./W_Global_Entry_tablegen.h"
#include "./W_Global_Section_tablegen.h"
#include "./W_Export_Entry_tablegen.h"
#include "./W_Export_Section_tablegen.h"
#include "./W_Start_Section_tablegen.h"
#include "./W_Elem_Segment_tablegen.h"
#include "./W_Element_Section_tablegen.h"
#include "./W_Local_Entry_tablegen.h"
#include "./W_Function_Body_tablegen.h"
#include "./W_Code_Section_tablegen.h"
#include "./W_Data_Segment_tablegen.h"
#include "./W_Data_Section_tablegen.h"
#include "./Wasm_Module_tablegen.h"
#include "./wasm_tables.h"

void reg_tablegen_tables(lua_State* __ls) {
	init_expr_t_register(__ls);
	lua_pop(__ls, 1);
	resizable_limit_t_register(__ls);
	lua_pop(__ls, 1);
	global_type_t_register(__ls);
	lua_pop(__ls, 1);
	table_type_t_register(__ls);
	lua_pop(__ls, 1);
	memory_type_t_register(__ls);
	lua_pop(__ls, 1);
	W_Type_Section_Entry_register(__ls);
	lua_pop(__ls, 1);
	W_Type_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Import_Section_Entry_register(__ls);
	lua_pop(__ls, 1);
	W_Import_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Function_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Table_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Memory_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Global_Entry_register(__ls);
	lua_pop(__ls, 1);
	W_Global_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Export_Entry_register(__ls);
	lua_pop(__ls, 1);
	W_Export_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Start_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Elem_Segment_register(__ls);
	lua_pop(__ls, 1);
	W_Element_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Local_Entry_register(__ls);
	lua_pop(__ls, 1);
	W_Function_Body_register(__ls);
	lua_pop(__ls, 1);
	W_Code_Section_register(__ls);
	lua_pop(__ls, 1);
	W_Data_Segment_register(__ls);
	lua_pop(__ls, 1);
	W_Data_Section_register(__ls);
	lua_pop(__ls, 1);
	Wasm_Module_register(__ls);
	lua_pop(__ls, 1);
}

