setmakepath("../test/bruisertest")
make("clean")
text = hijackmain()
file = io.open("../test/bruisertest/mutatant.cpp", "w")
print("------------------------------------------------------------------")
print(text)
print("------------------------------------------------------------------")
file:write(a)
file:close()
