-- automatically generated by luatablegen
local wasm = {}

setmetatable(init_expr_t, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(resizable_limit_t, {__call =
	function(self, arg0, arg1, arg2)
		local t = self.new(arg0, arg1, arg2)
		return t
	end
	}
)

setmetatable(global_type_t, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(table_type_t, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(memory_type_t, {__call =
	function(self, arg0)
		local t = self.new(arg0)
		return t
	end
	}
)

setmetatable(W_Type_Section_Entry, {__call =
	function(self, arg0, arg1, arg2, arg3, arg4)
		local t = self.new(arg0, arg1, arg2, arg3, arg4)
		return t
	end
	}
)

setmetatable(W_Type_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Import_Section_Entry, {__call =
	function(self, arg0, arg1, arg2, arg3, arg4, arg5)
		local t = self.new(arg0, arg1, arg2, arg3, arg4, arg5)
		return t
	end
	}
)

setmetatable(W_Import_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Function_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Table_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Memory_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Global_Entry, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Global_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Export_Entry, {__call =
	function(self, arg0, arg1, arg2, arg3)
		local t = self.new(arg0, arg1, arg2, arg3)
		return t
	end
	}
)

setmetatable(W_Export_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Start_Section, {__call =
	function(self, arg0)
		local t = self.new(arg0)
		return t
	end
	}
)

setmetatable(W_Elem_Segment, {__call =
	function(self, arg0, arg1, arg2, arg3)
		local t = self.new(arg0, arg1, arg2, arg3)
		return t
	end
	}
)

setmetatable(W_Element_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Local_Entry, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Function_Body, {__call =
	function(self, arg0, arg1, arg2, arg3)
		local t = self.new(arg0, arg1, arg2, arg3)
		return t
	end
	}
)

setmetatable(W_Code_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(W_Data_Segment, {__call =
	function(self, arg0, arg1, arg2, arg3)
		local t = self.new(arg0, arg1, arg2, arg3)
		return t
	end
	}
)

setmetatable(W_Data_Section, {__call =
	function(self, arg0, arg1)
		local t = self.new(arg0, arg1)
		return t
	end
	}
)

setmetatable(Wasm_Module, {__call =
	function(self, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
		local t = self.new(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
		return t
	end
	}
)

return wasm
